#!/bin/bash

read -p "Please enter a num" NUM

isPrime()
{

if [[ $1 == 1 || $1 == 2]]
 then
    echo "Prime"
fi

for (( i = 2; i <= $1/2; i++ ))  do

    if [[ $1 != $i &&  $(($1 % $i)) == 0]]
      then
        exit
    fi  
done

}

isPrime $NUM